### ISSUE TITLE
getIp(hostname) blocks - seems to be a bug in Dubbo2.6.1

### ISSUE THREAD

**Issue by shuguoxian** [apache/incubator-dubbo#1593] opened 2018-04-12 03:21 UTC
在Dubbo2.6.1的版本使用中，发现在启动时CPU直接飙升100%，经过内存堆栈分析，发现是在获取本机IP地址时阻塞。具体stack见附件stack.log。
 
目前解决方案：
设置hostname为当前ecs服务器的内网ip地址。
 
 
问题产生操作系统：阿里云centos6.8 [final。具体原因未知。]

内存堆栈见附件(http://note.youdao.com/noteshare?id=6511f213d04ec83676c4105df3953fe4&sub=9AA5BFECD27F460DA8AE5AB2CFDF8CF1)

**Comment by chickenlj** [comment] 2018-04-12 04:41
Which way do you use to specify the 'hostname' registered to registry. 

The jstack or heap dump link you provide is not available at this moment, we need those sources to locate the problem.

**Comment by chickenlj** [comment] 2018-04-12 04:54
Recommend subscribe to dev@dubbo.apache.org to discuss questions like this, just send your questions to this mail address, and we will guarantee a better and quicker reply there.
How to subscribe, see #1393.

Please use english.

**Comment by vangoleo** [comment] 2018-05-16 08:10
Can not reproduce this issue. Can set the hostname=xx.xx.xx.xx in /etc/hosts file to specify the ip to be registered to registry.

Please close this issue.

**Comment by chickenlj** [comment] 2018-05-18 06:18
Cannot reproduce, reopen if necessary.

**Closed by chickenlj** 2018-05-18 06:18 UTC
Labels: level/easy, priority/normal, type/suspicious
