### ISSUE TITLE
async 的优先级bug

### ISSUE THREAD

**Issue by summer9989** [apache/incubator-dubbo#380] opened 2017-02-23 06:48 UTC
假如我在provider 的 service 和 method都配置async 
service 为true ,method 为 false
```
<dubbo:service
		interface="cn.com.xxxxx.service.notification.NotificationSender"
		async="true" timeout="100000" ref="notificationSender">
		<dubbo:method name="getInactiveDevices" timeout="100000"
			async="false"></dubbo:method>
	</dubbo:service>
```

我本意是希望service 所有方法都async =true 异步, 除了getInactiveDevices方法,所以给它async =false

测试结果是getInactiveDevices也会变成async =true. 观察源码是因为async="false"时并不会在dubbo的url里出现,是因为默认值就是false的原因么?

所以我希望确认
1.我这种用法dubbo确实是不支持么?(即service大部分方法都async=true, 只有1,2个async=false,我单独method设它就好)

2.async =false,乃至check=false之类是默认值的设置,真的不会出现在dubbo url里?我特地去设的哦

**Comment by diecui1202** [comment] 2018-08-10 06:02
@summer9989 Could u pls provide a demo to reproduce this scenario ?

**Comment by carryxyh** [comment] 2018-09-11 03:44
hi @summer9989 
I will close this ISSUE because there is no feedback for a long time.
I suggest you:
1. Use the latest dubbo code
2. If you still have problems, please submit a new issue and provide the dubbo branch and demo

**Closed by carryxyh** 2018-09-11 03:44 UTC
