### ISSUE TITLE
Dubbo 2.6.3 server starts after showing 2.0.2

### ISSUE THREAD

**Issue by llx206** [apache/incubator-dubbo#2556] opened 2018-09-25 09:33 UTC
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.3
* Operating System version: windows
* Java version: 1.8

### Steps to reproduce this issue

1. incubator-dubbo-dubbo-2.6.3\dubbo-demo\dubbo-demo-provider
![image](https://user-images.githubusercontent.com/39985288/46005836-bec00100-c0e8-11e8-8fa2-10afcab88dca.png)
after run this main

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result
dubbo=2.6.3

### Actual Result

![image](https://user-images.githubusercontent.com/39985288/46005914-e6af6480-c0e8-11e8-9b9d-750115d21c47.png)

**Comment by diecui1202** [comment] 2018-09-25 09:35
@llx206 2.0.2 is the version of dubbo protocol, 2.6.3 is the version of maven jar.

**Comment by llx206** [comment] 2018-09-25 09:59
@diecui1202 ，why in the 2.6.2,  this show 
![image](https://user-images.githubusercontent.com/39985288/46007447-a0f49b00-c0ec-11e8-99c8-77bdc7825823.png)

May I ask if the meaning of the fields 2.6.2 and 2.6.3 has changed?

**Comment by zonghaishang** [comment] 2018-09-26 02:14
@llx206

Here is dubbo-2.6.2 code :

```
private void doExportUrlsFor1Protocol(ProtocolConfig protocolConfig, List<URL> registryURLs) {
  ...
  map.put(Constants.DUBBO_VERSION_KEY, Version.getVersion());
  ...
```

Here is dubbo-2.6.3 code :

```
private void doExportUrlsFor1Protocol(ProtocolConfig protocolConfig, List<URL> registryURLs) {
  ...
  map.put(Constants.DUBBO_VERSION_KEY, Version.getProtocolVersion());
  ...
```

duplicate of https://github.com/apache/incubator-dubbo/issues/2542

**Closed by zonghaishang** 2018-09-26 02:14 UTC
