### ISSUE TITLE
The version report to registry is 2.0.1 after dubbo 2.5.9

### ISSUE THREAD

**Issue by lanhuai** [apache/incubator-dubbo#1524] opened 2018-03-29 06:48 UTC
The `Dubbo version` report to registry is 2.0.1 after dubbo 2.5.9 and 2.5.10. 

It should be the same as the dubbo version i think.

**Comment by ralf0131** [comment] 2018-03-29 06:55
Hi, welcome!

It will be appreciated that you can provide a simple step to reproduce this issue.

**Comment by diecui1202** [comment] 2018-03-29 09:59
I debug the demo in the codebase, and get the following result:

![image](https://user-images.githubusercontent.com/1152291/38082858-8be66090-337a-11e8-8223-1428811cdd19.png)

The red rectangle show "dubbo=2.0.0", is this the problem?

**Comment by lanhuai** [comment] 2018-03-30 09:40
@diecui1202 Yes, this is the problem.

**Comment by lovepoem** [comment] 2018-04-02 11:18
https://github.com/apache/incubator-dubbo/blob/master/dubbo-common/src/main/java/com/alibaba/dubbo/common/Version.java   

Version.java read version from MANIFEST.MF or jar name.

Now you debug in classes generated by IDE, no MANIFEST.MF or jar name found

Must we support the IDEA debug environment?

We can refer this [Generate a Version.java file in Maven
](https://stackoverflow.com/questions/2469922/generate-a-version-java-file-in-maven)

**Comment by faicm** [comment] 2018-04-02 11:20
1 maven Compile and install  "dubbo-common"
2 Closing the “dubbo-common” project in IDE
And then it's going to be good

**Comment by cvictory** [comment] 2018-04-10 08:54
I found Implementation-verison and Specification-version in dubbo jar(version:2.6.1 ) is right.

And as @diecui1202 said, We will not change the value in register url. such as : registry://224.5.6.7:1234/com.alibaba.dubbo.registry.RegistryService?application=demo-provider&dubbo=2.0.0&pid=9796&qos.port=22222&registry=multicast&timestamp=1523350418885 .
The value `dubbo=2.0.0` will be kept.

**Comment by zonghaishang** [comment] 2018-04-11 07:41
@lovepoem

+1， "ide" can read the version correctly is a good suggestion.

**Comment by lovepoem** [comment] 2018-04-13 21:52
Duplicate of https://github.com/apache/incubator-dubbo/issues/1466

**Comment by chickenlj** [comment] 2018-04-25 12:12
Close this one.

**Closed by chickenlj** 2018-04-25 12:12 UTC
Labels: type/bug
