### ISSUE TITLE
May used the dubbo version for instead of protocol version is correct

### ISSUE THREAD

**Issue by sarins** [apache/incubator-dubbo#2698] opened 2018-10-29 02:48 UTC
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.4
* Operating System version: Mac OS/X
* Java version: 1.8

### Steps to reproduce this issue

1. checkout dubbo 2.6.2, see as below in the ServiceConfig.java
![51540780365_ pic](https://user-images.githubusercontent.com/1165129/47626728-89835480-db67-11e8-9c5d-73c3f3dfe2a1.jpg)
2. checkout dubbo 2.6.4, 
![71540780398_ pic](https://user-images.githubusercontent.com/1165129/47626757-a586f600-db67-11e8-959a-2a546453dcb7.jpg)
3. which one is correct for aboves?

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

I think correct result is looks like version 2.6.2

### Actual Result

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by jasonjoo2010** [comment] 2018-10-29 03:30
Some logic uses the version param in provider URL to decide whether using some new feature.
For example feature of attachments.

Now the protocol version is increased from 2.0.0 carefully and i think the `protocol version` should be used in registry from now on.

**Comment by beiwei30** [comment] 2018-10-29 06:33
the current behavior is changed on purpose, in order to keep inter-op among dubbo instances with the different versions.

**Comment by zonghaishang** [comment] 2018-10-29 06:33
duplicate of https://github.com/apache/incubator-dubbo/issues/2542

> Some logic uses the version param in provider URL to decide whether using some new feature.

+1

**Closed by beiwei30** 2018-10-29 06:33 UTC

**Comment by chickenlj** [comment] 2018-10-29 06:36
The change was bringed in 2.6.4 or earlier, the version number was split into two parts:
1.`getVersion()`, which is the only version used in Dubbo before 2.6.4, it represents the version of the jar package or the version number stored in MANIFEST.MF. This version will change along with each release.
2. `getProtocolVersion()`, newly created to represent the RPC protocol version, it will only change when there's incompatible RPC protocol upgrades.

I would suggest that `getProtocolVersion()` only being used internally by Dubbo framework itself.
