### ISSUE TITLE
2.7.0版的rest协议，无论是内嵌式或者外部集成式都不起作用。2.6.5版却没问题。

### ISSUE THREAD

**Issue by kunghsu1021** [apache/incubator-dubbo#3487] opened 2019-02-15 15:48 UTC
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0
* Operating System version: windows
* Java version: 1.8

### Steps to reproduce this issue

1. 参考dubbo官网的rest协议使用例子来模拟
http://dubbo.apache.org/zh-cn/docs/user/references/protocol/rest.html
2. 按照上面链接中说的写法，分别尝试2.6.5版和2.7.0版就能看出差别。2.6.5版发布的rest服务能正常被访问，而2.7.0版的rest服务不能被访问。

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?
2.7.0版的rest协议，无论是内嵌式(jetty或者tomcat)或者外部集成式（通过web.xml配置）都不起作用。2.6.5版却没问题。这是2.7.0版的一个bug.

这个bug会导致restful接口无法正常访问。

**Comment by kunghsu1021** [comment] 2019-02-15 15:53
i can provide a demo to reproduce this problem.

**Comment by kezhenxu94** [comment] 2019-02-15 16:01
可能与 #3445 相关

**Comment by kunghsu1021** [comment] 2019-02-15 16:05
https://github.com/kunghsu1021/dubborestdemo 样例demo @kezhenxu94  
这个bug会在2.7.1版修复吗？

**Comment by kezhenxu94** [comment] 2019-02-15 16:19
@kunghsu1021 关注一下 pr #3479

**Comment by chickenlj** [comment] 2019-02-18 02:54
Duplicate of #3445

**Closed** 2019-02-18 07:50 UTC
