### ISSUE TITLE
not support java 10

### ISSUE THREAD

**Issue by hank-whu** [apache/incubator-dubbo#1500] opened 2018-03-22 05:28 UTC
Can't start the dubbo server.

VM version: JDK 10, VM 10+46
OS version: Ubuntu 16.04 x64

**Comment by ralf0131** [comment] 2018-03-22 05:44
Hi, Welcome!

Can you provide more details, e.g. do you have stack trace?

**Comment by hank-whu** [comment] 2018-03-22 05:49
There's no exception, but not work. 
You can run the test:

**Comment by ralf0131** [comment] 2018-03-22 06:02
What JMH version are you using, is it Java 10 compatible?

**Comment by hank-whu** [comment] 2018-03-22 08:10
jmh 1.20, it's no problem

**Comment by hank-whu** [comment] 2018-04-08 09:59
嗯，搞明白了，不是dubbo 跟 java 10 的兼容性问题。
是 dubbo-2.6.1 跟 maven-assembly-plugin 的兼容性问题，退回到 dubbo-2.6.0 就没问题了。

**Comment by diecui1202** [comment] 2018-04-08 13:29
@hank-whu What's the detail compatible problem about Dubbo 2.6.1 and maven-assembly-plugin? Could you paste the exception stack trace here?

**Comment by hank-whu** [comment] 2018-04-09 03:54
```java
>java -jar dubbo-server-round-2-jar-with-dependencies.jar

Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/context/support/ClassPathXmlApplicationContext
        at benchmark.rpc.Server.main(Server.java:8)
Caused by: java.lang.ClassNotFoundException: org.springframework.context.support.ClassPathXmlApplicationContext
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 1 more
```

**Comment by hank-whu** [comment] 2018-04-09 03:57
eclipse 中启动是没问题的，打包成 dubbo-server-round-2-jar-with-dependencies.jar 就会抛错。

**Comment by diecui1202** [comment] 2018-04-10 03:26
@hank-whu I run this two server/client demo on my mac, and it's all ok. 

![image](https://user-images.githubusercontent.com/1152291/38534599-889c61ce-3cb1-11e8-8a07-1d6dfa85204d.png)

![image](https://user-images.githubusercontent.com/1152291/38534619-9757e7c4-3cb1-11e8-958c-b76ffa80d937.png)

![image](https://user-images.githubusercontent.com/1152291/38534631-a2c4e008-3cb1-11e8-89e0-bfc2ac25ee7d.png)

And my maven version is 3.3.9, my java version is: 

```
➜  ~ java -version
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```

So please check your maven and jdk10 env.

**Comment by ralf0131** [comment] 2018-04-10 03:43
@diecui1202 Please use text instead of pic as much as possible. Text is more search engine friendly.

**Comment by ralf0131** [comment] 2018-04-10 03:44
Looks like this issue is not reproducible, I am closing this issue now. Feel free to reopen it if you can reproduce it later.

**Closed by ralf0131** 2018-04-10 03:44 UTC

**Comment by hank-whu** [comment] 2018-04-10 05:26
@diecui1202 
现在那两个项目 pom.xml 里的 dubbo 版本是 2.6.0，你把里面的版本修改为 2.6.1 了吗？

**Comment by diecui1202** [comment] 2018-04-10 05:28
@hank-whu Yeah, I've changed it to 2.6.1 yet.

@ralf0131 Ok, I got it.

**Comment by hank-whu** [comment] 2018-04-10 05:47
@diecui1202 
我试了很多次，还是不行，你的 pom 文件可以贴上来吗？

**Comment by diecui1202** [comment] 2018-04-10 05:49
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>benchmark.rpc</groupId>
	<artifactId>dubbo-server</artifactId>
	<version>round-2</version>
	<packaging>jar</packaging>

	<name>dubbo-server</name>
	<url>http://maven.apache.org</url>

	<properties>
		<maven.compiler.source>1.9</maven.compiler.source>
		<maven.compiler.target>1.9</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<version.benchmark-base>round-2</version.benchmark-base>
		<version.dubbo>2.6.1</version.dubbo>
		<version.javakaffee>0.42</version.javakaffee>
	</properties>

	<dependencies>
		<dependency>
			<groupId>benchmark.rpc</groupId>
			<artifactId>benchmark-base</artifactId>
			<version>${version.benchmark-base}</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>dubbo</artifactId>
			<version>${version.dubbo}</version>
		</dependency>
		<dependency>
			<groupId>de.javakaffee</groupId>
			<artifactId>kryo-serializers</artifactId>
			<version>${version.javakaffee}</version>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>

	</dependencies>


	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<defaultLibBundleDir>lib</defaultLibBundleDir>
					<source>9</source>
					<target>9</target>
					<encoding>UTF-8</encoding>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.0.0</version>
				<configuration>
					<encoding>UTF-8</encoding>
				</configuration>
			</plugin>

			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.1.0</version>
				<configuration>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
					<archive>
						<manifest>
							<mainClass>benchmark.rpc.Server</mainClass>
						</manifest>
					</archive>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id> <!-- this is used for inheritance merges -->
						<phase>package</phase> <!-- bind to the packaging phase -->
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
		</resources>
	</build>
</project>
```

I just change version.dubbo to 2.6.1

**Comment by hank-whu** [comment] 2018-04-10 07:14
应该是我电脑 maven 的问题，删掉 maven 的 repository 后问题解决。
浪费大家时间了，多谢各位。
