### ISSUE TITLE
Docker not support host?

### ISSUE THREAD

**Issue by xiaoniao** [apache/incubator-dubbo#2704] opened 2018-10-29 11:01 UTC
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version:2.6.2
* Operating System version: mac 10.13.6
* Java version: 1.8

### Steps to reproduce this issue

1. in this example https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-docker
2. docker run -t --net=host dubbo-sample-docker:latest
3. server not start 
4. [DUBBO] Could not get local host ip address, will use 127.0.0.1 instead., dubbo version: 2.6.2, current host: 127.0.0.1

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
support docker host network

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
ERROR 1 --- [           main] com.alibaba.dubbo.common.utils.NetUtils  :  [DUBBO] Could not get local host ip address, will use 127.0.0.1 instead., dubbo version: 2.6.2, current host: 127.0.0.1

```

**Comment by zonghaishang** [comment] 2018-10-31 15:32
duplicate of https://github.com/apache/incubator-dubbo/issues/1441, https://github.com/apache/incubator-dubbo/issues/1432

**Closed by zonghaishang** 2018-10-31 15:32 UTC
