### ISSUE TITLE
dubbo在调节权重时，编辑保存后，端口号丢失

### ISSUE THREAD

**Issue by yishunli** [apache/incubator-dubbo#2613] opened 2018-10-09 02:32 UTC
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.5.2
* Operating System version: linux
* Java version:java 8

### Steps to reproduce this issue

1. dubbo管理后台，先选中一个服务提供者，选择半权
2. 在权重调节的标签下可以看到上一步设置的半权
3. 点击编辑，设定权重值，保存后，只剩下提供者的ip，端口号丢失

### Expected Result

正常调节权重

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by lexburner** [comment] 2018-10-16 11:49
Hi，i try to re-produce your problem，but everything looks ok. Here is my code version:

```
dubbo version: 2.6.0
incubator-dubbo-ops version: lastest  branch: master 
```

As your report says: your dubbo version is  3.5.2. Is it a internal dubbo version or wrote wrongly?
try to clone this version and try again `https://github.com/apache/incubator-dubbo-ops/tree/master`. Let me know if also questions.

**Comment by beiwei30** [comment] 2019-02-11 09:26
feel free to re-open it if you still can reproduce. I will close it since @lexburner cannot reproduce it.

**Closed by beiwei30** 2019-02-11 09:26 UTC
Labels: dubbo-ops
