### ISSUE TITLE
是否增加eureka注册中心的支持

### ISSUE THREAD

**Issue by jqncc** [apache/incubator-dubbo#1960] opened 2018-06-19 13:23 UTC
是否增加eureka注册中心的支持
how do supported eureka as service discovery?

**Comment by kimmking** [comment] 2018-06-19 14:11
that's a good idea

**Comment by diecui1202** [comment] 2018-06-20 07:15
hi, @jqncc support eureka is in our roadmap, bug now it hasn't scheduled. We are happy to see your suggestion or PR.

**Comment by dreamquster** [comment] 2018-06-21 13:43
@diecui1202 , I'm interesting in this. Howerver,
How to pass EurekaServerServiceUrls from URI type in dubbo registry? In eureka,  EurekaServerServiceUrls is map and has multiple zones and service URI at every zone as following:

eurekaServerServiceUrls:  
     defaultZone: http://user:${eureka.password}@localhost:8761/eureka/, http://${ip}:${port}/registry/eureka/  
     eastAmericanZone: http://201.30.433:9683/eureka, ...,  
     ...   

It's ugly to flatten it to string like this:
eurekaServerServiceUrls=defaultZone:http://user:${eureka.password}@localhost:8761/eureka/,http://${ip}:${port}/registry/eureka/;eastAmericanZone: http://201.30.433:9683/eureka, ...,

 

It's suitable to add extra xml label?

**Comment by yidinshi** [comment] 2018-06-23 04:11
请支持一下，方便集成前端api 网关

**Comment by chickenlj** [comment] 2018-07-10 06:13
Duplicate of #1981

**Closed by chickenlj** 2018-07-10 06:13 UTC
