### ISSUE TITLE
Server side loadbalance problem

### ISSUE THREAD

**Issue by freeseawind** [apache/incubator-dubbo#2419] opened 2018-09-01 06:54 UTC
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: win7
* Java version: 1.8

#### Problem one

I want to test pseudo cluster, I create service like follow code :

```
public interface DemoService
{
    String sayHello(String name);
}
```

implement service interface  as follows, both loadbalance strategies are random：

```
@Service(timeout = 5000, loadbalance="random")
public class DemoServiceImpl implements DemoService
{
    @Override
    public String sayHello(String name)
    {
        return "Service1 -> Hello " + name;
    }
}
```

```
@Service(timeout = 5000, loadbalance="random")
public class DemoServiceImpl2 implements DemoService
{
    @Override
    public String sayHello(String name)
    {
        return "Service2 -> Hello " + name;
    }
}
```
I start one appliction to test it.

### Expected Result

* random return "Service1" and "Service2" . 

### Actual Result

* alway return "Service2"

#### Problem two

change one implement loadbalance stragy as follow:

```
@Service(timeout = 5000, loadbalance="consistenthash")
public class DemoServiceImpl implements DemoService
{
    @Override
    public String sayHello(String name)
    {
        return "Service1 -> Hello " + name;
    }
}
```

### Expected Result

* random return "Service1" and "Service2" . 

### Actual Result

* alway return "Service1"

### Question

I don't know how dubbo it works. but it is very strange , it always use consistenthash stragy.

Dubbo provide client and server side loadbalance stragy , Who is at work.

As I know，dubbo has no central node coordinator,  may be is client side effect. If remove server side loadblance stragy or improve it ?

could not provid unique way to use  loadbalance

* Single loadbalance stragy
* Mixed loadbalance stragy

@ulinkwo @justinmclean @lonre @ke4qqq @gmcdonald @carryxyh

**Comment by carryxyh** [comment] 2018-09-01 07:35
Hi, I will check the issue first.

**Comment by freeseawind** [comment] 2018-09-02 02:25
@carryxyh 

### demo reproduce this problem
https://github.com/freeseawind/copycat-dubbo

###  blog link
https://www.jianshu.com/p/08718775f162

**Comment by lexburner** [comment] 2018-09-04 02:37
I have reviewed your code and have a general understanding of your problem , here is my opinion (just consider me as a discusser ). 

`pseudo cluster` of dubbo is a fresh definition occur to me, and the way to test loadbalance feature is also debatable. 

Two implementations of `DemoService` may distinguish by `group` or `version` , otherwise these tow implementations are ambiguous. A crucial point to note is that dubbo can only consider `interface` as provider, if we don't distinguish manually.

`loadbalance` feature may be considered as some providers deploy on different machines or different port at the same machine. Not the two implementations in one Spring IOC context.

Maybe I misunderstand your expression, if so, let me know.

**Comment by freeseawind** [comment] 2018-09-04 02:41
@lexburner you can change Dubboscane to start two application provider with different port

**Comment by freeseawind** [comment] 2018-09-04 02:47
@lexburner pseudo cluster most run on different port or machines. What makes me puzzled is dubbo registe two provider on zookeeper.

see my problem on blog: [Dubbo loadbalance](https://www.jianshu.com/p/08718775f162)

**Comment by lexburner** [comment] 2018-09-04 03:39
@freeseawind GOT it. 
```
dubbo://172.19.6.139:20881/github.freeseawind.service.DemoService?anyhost=true&application=provider-test&dubbo=2.6.2&generic=false&interface=github.freeseawind.service.DemoService&loadbalance=random&methods=sayHello&pid=3527&side=provider&timeout=5000&timestamp=1536031418472,
dubbo://172.19.6.139:20881/github.freeseawind.service.DemoService?anyhost=true&application=provider-test&dubbo=2.6.2&generic=false&interface=github.freeseawind.service.DemoService&loadbalance=random&methods=sayHello&pid=3527&side=provider&timeout=5000&timestamp=1536031419012
```
notice the last attribute `timestamp` is different, it means that the two implementations both trigger the registry operation. So in the zookeeper, you can see two providers, while in the spring IOC context, it also has two implementations. 

The problem is that Dubbo invoker can not distinguish the two provider because their main attributes are the same. While dubbo try to find the ref in the Spring IOC context, one of the them is always selected.

I think that it is dubbo user's responsibility to set enough info if two providers are exist in the same context.

more details can reference the `com.alibaba.dubbo.config.spring.ServiceBean`. It implements `InitializingBean` and `ApplicationListener`, you can know the initialization process by debuging into two method `afterPropertiesSet()` and `onApplicationEvent()`.

**Comment by carryxyh** [comment] 2018-09-04 03:48
Hi, @freeseawind 
As @lexburner said, you can retest with two spring containers.
I have check the unit test and I can not reproduce this problem.

**Comment by freeseawind** [comment] 2018-09-04 06:13
@lexburner How to distinguish between two service providers when it's host and port are same.(include service interface).
pseudo cluster Just one of the problems

#### I have three misunderstand problem:

* client side or server side hight priority.
* mixed loadbalance stragy priority.
* single web container pseudo cluster.

the concept of load balancing is blurred here.

**Comment by carryxyh** [comment] 2018-09-04 06:44
`client side or server side hight priority.` Check the dubbo-user-book.

`mixed loadbalance stragy priority.`
This is incorrect, but if it appeared, a random one(I mean not RandomLoadBalance but random one of all the LoadBalance) may be used. The code to init loadbalance is: 

```
if (CollectionUtils.isNotEmpty(invokers)) {
    return ExtensionLoader.getExtensionLoader(LoadBalance.class).getExtension(invokers.get(0).getUrl()
            .getMethodParameter(RpcUtils.getMethodName(invocation), Constants.LOADBALANCE_KEY, Constants.DEFAULT_LOADBALANCE));
}
```
The important code is `invokers.get(0).getURL()`. 

`How to distinguish between two service providers when it's host and port are same.(include service interface).`  Maybe use 'group'.

**Comment by carryxyh** [comment] 2018-09-04 06:46
Alternatively, you can send an email to dev@dubbo.apache.org for help. :)

**Comment by carryxyh** [comment] 2018-09-04 11:53
Hi, @freeseawind 
Do u have any questions with this issue?
If not, I will close it.

**Comment by freeseawind** [comment] 2018-09-04 11:57
@carryxyh  I think server side loadbalace is strangy. compare with nginx、lvs etc.

**Comment by carryxyh** [comment] 2018-09-04 12:04
Of course, there are specific examples to view the official documentation. :)

**Closed by carryxyh** 2018-09-04 12:04 UTC

**Comment by freeseawind** [comment] 2018-09-04 12:06
@carryxyh  official documentation no instructions provided

**Comment by carryxyh** [comment] 2018-09-04 12:15
Find it from here, if it still doesn't, you can submit pr to complete the example.
https://github.com/dubbo/dubbo-samples

**Comment by carryxyh** [comment] 2018-09-04 13:29
Your understanding of the loadbalance parameter on the server side is wrong. The loadbalance attribute on the server takes effect when it is not configured on the consumer side.

Please see the Dubbo official manual "Configuration Coverage Relationship" chapter.
If you have other questions, resubmit an issue. If you still don't understand, please send an email to the community for help.

**Comment by freeseawind** [comment] 2018-09-04 13:37
there is not Configuration Coverage Relationship chapter


![4d00da e52x9cv _m e x](https://user-images.githubusercontent.com/19760912/45034639-a54c0c00-b08a-11e8-9973-07ab19611c61.png)

**Comment by freeseawind** [comment] 2018-09-04 13:41
@carryxyh loadbalance parameter on provider is not a good idea. 
Beacause provider is interface implement, will cause problems with the hybrid strategy.
