### ISSUE TITLE
Got out of memory when building the source code

### ISSUE THREAD

**Issue by WillemJiang** [apache/incubator-dubbo#1821] opened 2018-05-21 02:32 UTC
I tried to build the 2.6.2 source code by running "mvn clean install" from the route, I got the out of memory here. If I comment out the checkstyle check,  I can run the test and build the kit.

Here is my box information:
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T15:58:13+08:00)
Maven home: /opt/apache-maven-3.5.2
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"

**Comment by chickenlj** [comment] 2018-08-03 07:55
I guess it's mainly caused by the [rat](https://github.com/apache/incubator-dubbo/blob/413a2a0288d0b0800234132aff9f7c5f3803b633/pom.xml#L496) and [style](https://github.com/apache/incubator-dubbo/blob/413a2a0288d0b0800234132aff9f7c5f3803b633/pom.xml#L248) plugin.

I have set them closed by default and only open on travis.
https://github.com/apache/incubator-dubbo/blob/413a2a0288d0b0800234132aff9f7c5f3803b633/pom.xml#L124

**Closed by chickenlj** 2018-08-03 07:55 UTC
